[package]
name = "codex-api-reqwests"
version = "1.0.0"
edition = "2024"

[dependencies]
async-from = { version = "^0.1", git = "https://github.com/rad10/async-convert.git", default-features = false, optional = true }
codex-api-lib = { version = "^1.0", path = "../codex-api-lib", default-features = false }
codex-api-types = { version = "^0.1", path = "../codex-api-types", default-features = false, features = ["serde"] }
futures = { version = "0.3.33", optional = true, default-features = false }
http = { version = "^1", default-features = false }
regex-lite = { version = "^0.1", default-features = false, features = ["std", "string"] }
reqwest = { version = "^0.13", default-features = false, features = ["json", "query"] }
reqwest-middleware = { version = "^0", default-features = false, optional = true, features = ["json", "query"] }
serde = { version = "^1", default-features = false }
serde_json = "^1"
url = { version = "^2.5", default-features = false }
uuid = { version = "^1", default-features = false, features = ["v4"] }

[features]
default = ["std", "js"]
std = ["codex-api-lib/std", "futures?/std"]
js = ["codex-api-lib/js", "uuid/js"]
stream = ["reqwest/stream", "dep:futures"]
sync = ["codex-api-lib/sync", "reqwest/blocking"]
async = ["codex-api-lib/async", "dep:async-from"]
threaded = ["async", "codex-api-lib/threaded", "async-from/wasm"]
dynamic = ["async", "codex-api-lib/boxed"]
# Reqwest features
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls", "reqwest-middleware?/rustls"]
middleware = ["async", "dep:reqwest-middleware"]
